# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b82f6a0c26a5a544fdd0926b3b2844ae01b43208037da1a575f6523e85291e0935fd08fde890c4dfa9825999277c3a0e96a93fde8c6d216e871a1ca4dd56d13f

test:
  secret_key_base: 9987a3dc679433c1ed337a8a8fbb35c47d91fd930e8cba598159e2c7cdac7cfac4d895ce203b7e23e3efad7646ae8ae4a4daae8f30653eb9e1617a243594f619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
